# Generated by Django 6.0.7 on 2026-08-02 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг (cakes, bakery и т.д.)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram юзернейм')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес / Ориентир')),
                ('lat', models.FloatField(verbose_name='Широта (Lat)')),
                ('lng', models.FloatField(verbose_name='Долгота (Lng)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Общая сумма')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'Готовится'), ('DELIVERING', 'В пути'), ('COMPLETED', 'Выполнен'), ('CANCELLED', 'Отменен')], default='NEW', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Товар')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Цена за ед.')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Цена (сум)')),
                ('rating', models.FloatField(default=5.0, verbose_name='Рейтинг')),
                ('weight', models.CharField(max_length=50, verbose_name='Вес/Объем (например: 1.5 кг)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(max_length=500, verbose_name='Ссылка на изображение')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
