# Generated by Django 6.0.7 on 2026-08-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_image_url_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=500, upload_to='', verbose_name='Ссылка на изображение'),
        ),
    ]
