# Generated by Django 6.0.7 on 2026-08-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default='2026-08-12', verbose_name='Дата доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(choices=[('10:00 - 12:00', '10:00 - 12:00 (Утро)'), ('12:00 - 15:00', '12:00 - 15:00 (Обед)'), ('15:00 - 18:00', '15:00 - 18:00 (День)'), ('18:00 - 21:00', '18:00 - 21:00 (Вечер)')], default='12:00 - 15:00', max_length=30, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (Lat)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (Lng)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram юзернейм'),
        ),
    ]
