# Generated by Django 6.0.7 on 2026-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_delivery_date_order_delivery_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(choices=[('10:00 - 12:00', '10:00 - 12:00 (Утро)'), ('12:00 - 15:00', '12:00 - 15:00 (Обед)'), ('15:00 - 18:00', '15:00 - 18:00 (День)'), ('18:00 - 21:00', '18:00 - 21:00 (Вечер)')], default='12:00 - 15:00', max_length=30, verbose_name='Слот времени'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=500, upload_to='products/', verbose_name='Изображение товара'),
        ),
    ]
